### PR TITLE
Add Dockerfile and Github Actions workflow for building and pushing Docker container to Docker Hub

### PR DESCRIPTION
**Pull request by peterk87**
Hello!

This PR adds:

- a `Dockerfile` for building a Docker container for Pangolin and its dependencies
- a Github Actions workflow for building an image and pushing it to [Docker Hub](https://hub.docker.com/)

I currently have the Docker Hub organization or Docker ID set as `covlineages` (which [doesn't exist yet](https://hub.docker.com/u/covlineages)). Docker Hub doesn't allow dashes in the [Docker ID](https://docs.docker.com/docker-id/#register-for-a-docker-id) so had to remove the dash.

If a Docker Hub org/user is created (e.g. `covlineages`), then to enable pushing, in this repo's settings, you need to set the following secrets:

- `DOCKERHUB_USERNAME`: Docker Hub username
- `DOCKERHUB_PASS`: Docker Hub password

The size of the Docker image is 1.05GB

## Testing

Below are some commands to test the proposed additions:

```bash
git clone -b add-docker https://github.com/peterk87/pangolin
cd pangolin
# build Docker container with tag covlineages/pangolin
DOCKER_BUILDKIT=1 docker build -t covlineages/pangolin .
# check version of pangolin in newly created docker container
docker run --rm covlineages/pangolin pangolin --version
# run on test data with docker container "pangolin"
docker run \
  -v $PWD:/tmp/ \
  --user $(id -u):$(id -g) \
  --workdir /tmp/ \
  covlineages/pangolin \
  pangolin pangolin/test/test_seqs.fasta
# should output to lineage_report.csv
cat lineage_report.csv
# taxon,lineage,probability,pangoLEARN_version,status,note
# Wuhan/WH04/2020,A,1.0,2020-12-17,passed_qc,
# Japan/DP0779/2020|EPI_ISL_416626||Japan|unknown||2020-02-17,B,1.0,2020-12-17,passed_qc,
# USA/NY-NYUMC7/2020|EPI_ISL_418192||USA|New_York|Manhattan|2020-03-16,B.1.314,1.0,2020-12-17,passed_qc,
# This_seq_has_no_seq,None,0,2020-12-17,fail,seq_len:0
# This_seq_is_too_short,None,0,2020-12-17,fail,seq_len:2997
# This_seq_has_lots_of_Ns,None,0,2020-12-17,fail,N_content:0.98
# This_seq_is_literally_just_N,None,0,2020-12-17,fail,N_content:1.0
# issue_57_torsten_seq,None,0,2020-12-17,fail,failed to map
# This_seq_has_6000_Ns_in_18000_bases,None,0,2020-12-17,fail,failed to map
```

## Why?

Easier integration with workflow managers such as Nextflow, Snakemake and others that can use Docker containers.

### Example Nextflow workflow

Below is a very basic Nextflow workflow to run Pangolin on some input FASTA files using the Docker container built above tagged as "pangolin" (see `nextflow.config`).

Usage:

```bash
nextflow run main.nf -profile docker --input pangolin/test/test_seqs.fasta
```

with Pangolin output and logs in "$PWD/results/pangolin/"

Once the image is on Docker Hub, it would also be possible to the run workflow with a [Singularity](https://sylabs.io/guides/3.7/user-guide/introduction.html) container automatically created from the Docker container for execution on an HPC cluster (e.g. `nextflow run main.nf -profile singularity ...`).

`main.nf` workflow definition:

```nextflow
#!/usr/bin/env nextflow
nextflow.enable.dsl=2

params.outdir = "results"
params.input = "*.fasta"

process PANGOLIN {
  publishDir "${params.outdir}/pangolin",
             pattern: "*.csv",
             mode: 'copy'
  publishDir "${params.outdir}/pangolin",
             pattern: ".command.log",
             saveAs: { "pangolin-${input}.log" },
             mode: 'copy'

  input:
  path(input)

  output:
  path '*-pangolin-lineage_report.csv'
  path '.command.log'

  script:
  """
  pangolin \\
    $input \\
    -t ${task.cpus} \\
    --verbose \\
    --outfile ${input}-pangolin-lineage_report.csv
  """
}


workflow {
  Channel.fromPath(params.input) | PANGOLIN
}
```

`nextflow.config` workflow config:

```nextflow
process {
  withName: PANGOLIN {
    // using locally build pangolin container built with:
    // $ DOCKER_BUILDKIT=1 docker build -t covlineages/pangolin .
    // Otherwise, it should auto-pull from Docker Hub
    container = 'covlineages/pangolin'
    // It would be better to specify the exact version of pangolin desired, e.g.
    // container = 'covlineages/pangolin:2.1.2'
    cpus = 4
  }
}

profiles {
  docker {
    docker.enabled = true
    docker.runOptions = '-u \$(id -u):\$(id -g)'
  }
  singularity {
    singularity.enabled = true
    singularity.autoMounts = true
  }
}
```

### CODE REVIEW

**Comment by hoelzer** [comment]
great work! (I just stumbled over this bc/ we might also need a container for Pangolin including the recent lineages soonish)

**Comment by peterk87** [comment]
Thanks @hoelzer ! Our group has a need for an up-to-date containerized Pangolin so I've been trying to keep [my fork](https://github.com/peterk87/pangolin) of Pangolin in sync with the official repo. I have it setup with the changes in this PR so there's automated building of Pangolin Docker container images on commits to master and published releases. The Docker containers can be found at https://hub.docker.com/r/peterk87/pangolin/tags?page=1&ordering=last_updated

**Comment by aineniamh** [comment]
Hi both! We're happy to do this, I don't personally have experience using Docker containers, but @emilyscher does and she's happy to help merge in this PR, we just need to sort out the secrets etc.

**Comment by peterk87** [comment]
Hi @aineniamh that's great! 

For setting up secrets, you'd just need to go to repo settings to add "New repository secret". It should look something like this once everything is setup:

image

The Github Actions workflow should be able to access the values for those secrets to set some env vars:

https://github.com/cov-lineages/pangolin/blob/5f66da0549c442d87a62838dbc482071ea3a947f/.github/workflows/push_dockerhub.yml#L18-L20

For the Docker container, I set it to use Alpine with Miniconda3 using the official Docker container from ContinuumIO, which has Python 3.8.5 and pip already setup for simplicity and to try to cut down the size of the container. Pangolin seems to work great with Python 3.8.5, but if only up to Python 3.7 is supported then the following lines could be removed from the `Dockerfile` so that the specified versions of Python and pip are installed:

https://github.com/cov-lineages/pangolin/blob/5f66da0549c442d87a62838dbc482071ea3a947f/Dockerfile#L12-L13

**Comment by aineniamh** [comment]
So, I've added the secrets in now, and merged. Hope this works okay? If not just let me know and I can fix it!

**Comment by peterk87** [comment]
That's great @aineniamh! 

It should be automatic now so whenever a new release is published, a new image will be built and pushed to Docker Hub with the release tag (e.g. `v2.1.6`), or if there are commits to the dev branch then a new image will be built and pushed with the `dev` tag. 

Also, in Docker Hub, you can setup automatic builds of a new `latest` image whenever there are new commits pushed to master branch in the Pangolin Github repo.

**Pull request merged**
