### PR TITLE
add decompression of input files, fixes #432

### LINKED ISSUE #432: not working with compressed files
Hello! I am having trouble working with compressed files (`xz` in my case), which used to be automatically detected before. I am using `pangolin 4.0.5`, and the file has the proper `xz` suffix. 

Here is the full output:

```
****
Pangolin running in usher mode.
****
Maximum ambiguity allowed is 0.5.
****
Query file:     /usr/users/QIB_fr005/deolivl/Academic/Quadram/021.ncov/220307.react_omicron/05.update_wave19_0404/09.omicron_recombinant_0411/../../00.received/05.w13_19.nonrecombinant.fasta.xz
****
Data files found:
usher_pb:       /usr/users/QIB_fr005/deolivl/local/miniconda3/lib/python3.7/site-packages/pangolin_data/data/lineageTree.pb
****
Job stats:
job                      count    min threads    max threads
---------------------  -------  -------------  -------------
align_to_reference           1              1              1
all                          1              1              1
cache_sequence_assign        1              1              1
create_seq_hash              1              1              1
get_constellations           1              1              1
merged_info                  1              1              1
scorpio                      1              1              1
sequence_qc                  1              1              1
total                        8              1              1

[Wed Apr 13 11:49:28 2022]
Error in rule align_to_reference:
    jobid: 1
    output: /tmp/tmpjt4nustg/alignment.fasta
    log: /tmp/tmpjt4nustg/logs/minimap2_sam.log (check log file(s) for error message)
    shell:

        awk '{ if ($0 !~ /^>/) { gsub("-", "",$0); } print $0; }' "/usr/users/QIB_fr005/deolivl/Academic/Quadram/021.ncov/220307.react_omicron/05.update_wave19_0404/09.omicron_recombinant_0411/../../00.received/05
.w13_19.nonrecombinant.fasta.xz" |         awk '{ { gsub(" ", "_",$0); } { gsub(",", "_",$0); } print $0; }'  |         minimap2 -a -x asm20 --sam-hit-only --secondary=no --score-N=0  -t  1 /usr/users/QIB_fr005/de
olivl/local/miniconda3/lib/python3.7/site-packages/pangolin/data/reference.fasta - -o /tmp/tmpjt4nustg/mapped.sam &> /tmp/tmpjt4nustg/logs/minimap2_sam.log
        gofasta sam toMultiAlign             -s /tmp/tmpjt4nustg/mapped.sam             -t 1             --reference /usr/users/QIB_fr005/deolivl/local/miniconda3/lib/python3.7/site-packages/pangolin/data/referenc
e.fasta             --trimstart 265             --trimend 29674             --trim             --pad > '/tmp/tmpjt4nustg/alignment.fasta'

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


Exiting because a job execution failed. Look above for error message
```
(If I uncompress the file then everything goes smooth)

cheers,
Leo

### PR DESCRIPTION
**Pull request by pcjentsch**
The workaround is just to pipe into the pangolin command from `xz` or `gzip`, but since pangolin seems to partially support `.xz` and `.gz` inputs (in the input checking logic), I figured it would be helpful to add this.

Please let me know if there's anything I should fix, or if there is a better way to add this functionality!

### CODE REVIEW

**Comment by AngieHinrichs** [comment]
Thanks so much @pcjentsch for contributing this!  It mostly looks great but I have a couple concerns which I think can be easily addressed:

1. Many lines of shell commands are duplicated with only a small modification at the beginning of the command pipeline.  In general, duplicating lines of code makes the code less maintainable because if a change needs to be made in the future, it will have to be applied in three different places.  The command pipeline is a string passed to the `shell` function.  By defining the unchanged part of the command pipeline string only once, and changing only the start of the string, there can still be only one call to the `shell` function and it will be more clear which part of the command pipeline is different between the three cases.

2. Instead of passing the number of cores to xz, I think those cores should be left for use by the command later in the pipeline that is already using multiple cores.  (Technically pangolin is already exceeding the number of cores specified by running multiple commands in parallel via the pipeline while telling one of the commands to use the full number of cores, but that's not too bad.  This would double the number of cores specified, although xz's ability to use multiple threads when decompressing depends on how many threads were used when compressing...).

**Comment by pcjentsch** [comment]
Both good points, hopefully they have been addressed by my latest commit, thanks!

**Comment by AngieHinrichs** [comment]
Thanks, looking better now!  I have one more request: can you use `cat` instead of `<` for this line?:
```
            shell_command = "< \"{input.fasta}\"" + shell_command
```
When I run these 3 commands, I see the expected output from the second command (with `cat`) but not the third command (with `<`):
```
echo "some stuff" > /tmp/testfile
cat /tmp/testfile
< /tmp/testfile
```

**Comment by pcjentsch** [comment]
Certainly! I used the `<` operator because it [apparently has better performance](https://stackoverflow.com/questions/29988010/efficient-way-to-pipe-file-contents-to-program)), but `cat` is probably not the bottleneck here anyway.

I think your code example does not work because `cat` prints the contents of its argument to `STDOUT`, while `<` just points `STDIN` to ` /tmp/testfile/` (and therefore does not print anything). 

You can do this:
```
❯ echo $(< /tmp/testfile)

some stuff
❯ echo $(cat /tmp/testfile)

some stuff
```

**Comment by AngieHinrichs** [comment]
Thanks!  We need the contents of the file to be printed to STDOUT -- otherwise the rest of the command pipe has no input.
```
cat /tmp/testfile | awk '{print "The pipeline sees " $0;}'
< /tmp/testfile | awk '{print "The pipeline sees " $0;}'
```
@aineniamh this looks good to me now (though I have not tested it locally).

**Comment by pcjentsch** [comment]
ah right, thanks for catching that!

**Review by aineniamh — APPROVED** [review]
This looks really great!

**Comment by aineniamh** [comment]
In general, the giant awk command we've got there makes me slightly ill- but it was the only way I could think of streaming the input without writing the input file out again (which is what we used to do), and minimap2 doesn't enjoy spaces in the sequence name and if we don't handle pre-existing gaps in the alignment, they get replaced with N in the output. 

But this seems great and it's passing all the tests!

**Pull request merged**
