### PR TITLE
Assignment cache: optional install, usher analysis mode only

### PR DESCRIPTION
**Pull request by AngieHinrichs**
This restores some commented-out additions from @rmcolq's first commit in the handle_cache branch, and moves the contents of assignment_cache.smk into usher.smk, with some modifications:

* By default, the pangolin-assignment repo is not installed, in order to avoid slowing down installation and updating when we expect the cache to be used rarely (only when running with large numbers of sequences, most of which are already in public repositories).
  * `pangolin --update` and `pangolin --update-data` ignore pangolin-assignments if it is missing
  * `pangolin --use-assignment-cache` exits with an error message saying that `pangolin --add-assignment-cache` must be called first

* pangolin-assignment can be added to the installation by running `pangolin --add-assignment-cache`.  After that:
  * `pangolin --update` and `pangolin --update-data` update pangolin-assignments along with pangolin-data
  * `pangolin --use-assignment-cache` applies the cache from pangolin-assignment.  Before starting, it compares release versions of pangolin-data and pangolin-assignments and exits with an error if they are inconsistent.
  * If the `--use-assignment-cache` option is not used then the assignment cache is ignored and all sequences go through inference as usual.
  * The pangolin-assignment repo can be removed from the installation by running
    ```
    conda activate pangolin
    pip uninstall pangolin-assignment
    ```
    That restores the installation to its pre-`--add-assignement-cache` state.

* Development option `--assignment-cache FILE` works regardless of whether pangolin-assignment is installed

### CODE REVIEW

**Review by rmcolq — COMMENTED** [review]
I don't think I see a good way around it, but `get_cached_dict` looks like it will load the entire cache into memory. It will be bigger than the cache for the designated set. Just going to give this a spin now.

**Comment by rmcolq** [comment]
This is a massive improvement time-wise. I just tried it with 250k sequences and 10 threads and it took 1.5 hours down from 8, and with a smaller maximum resident set size so really great!

Looking at the differences in outputs (I've may have other changes in my env, hopefully not...) I can see entries like "scorpio replaced lineage inference AY.25" in the new output, but not "not supported by scorpio". Howe does this cache mode interact with scorpio exactly? Are you running scorpio when you generate the cache? I would have thought better not to (do we have a skip scorpio flag? If not we should).

**Comment by AngieHinrichs** [comment]
>  `get_cached_dict` looks like it will load the entire cache into memory. 

It's loading all assignments from the cache into memory, not the original cache.  So if you're running on 10,000 sequences then it will load at most 10,000 results.

**Comment by rmcolq** [comment]
I'm taking a look at adding a skip scorpio flag now

**Pull request merged**
